### ISSUE TITLE
Plugin not published on Npm?

### ISSUE THREAD

**Issue by ebourmalo** [feathersjs/feathers-sync#1]
Hey, I couldn't find this plugin on Npm so I had to set the github repo in my `package.json` to get it installed. Any chance to see it on Npm :) ? Thanks

**Comment by ekryski** [comment]
Yup it's not published yet. We've been meaning to get a guide up for using it. A redis one is also planned. Not sure if this is totally ready for use. @daffl would know.

**Comment by daffl** [comment]
Basic functionality works I think (although the tests were failing for me locally so I have to look into that). I've been thinking to rename it to `feathers-sync` before publishing, too.

**Comment by ebourmalo** [comment]
Actually, I tested it yesterday and it doesn't work as it is.

I have to use a forked version of the main dependency mubsub (https://github.com/znetstar/mubsub) because the original repo was not updated for the current version of mongo (2.x). A PR https://github.com/scttnlsn/mubsub/pull/38 waits for fixing the problems.

**Comment by ebourmalo** [comment]
I like the `feathers-sync` name @daffl :) 
Thank you for proposing all these awesome plugins!

**Comment by mastertinner** [comment]
Now with Redis, this plugin should be ready to be published to npm, no?

**Comment by daffl** [comment]
Once it's upgraded to the new plugin infrastructure and the API is finalized (see https://github.com/feathersjs/feathers-sync/pull/2#issuecomment-176250255). Probably some time this evening.

**Comment by mastertinner** [comment]
Awesome, thanks @daffl!

**Comment by daffl** [comment]
I just published the current master as [feathers-sync@0.1.0](https://www.npmjs.com/package/feathers-sync). I will continue working on the updates I mentioned.
