### ISSUE TITLE
Event not fired in socket on client

### ISSUE THREAD

**Issue by nicksrandall** [feathersjs/feathers-sync#11]
When using this plugin, I can see that when an action happens, the event is fired and received by the server, but it does not get received on the client via the socket connection. When I remove this plugin, the socket events fire again. Am I missing something?

Any help is appreciated!

**Comment by daffl** [comment]
What does your setup look like? Is the database connection working?

**Comment by ekryski** [comment]
@nicksrandall do you mind posting a gist of your setup? We'd love to verify if this is a legit bug or not. Otherwise we are just going to close this out in the next day or two.

**Comment by daffl** [comment]
Going to close this since we don't have more information to work with and from everything I could tell it works.
