### ISSUE TITLE
Error: Cannot find module 'feathers-sync'

### ISSUE THREAD

**Issue by mastertinner** [feathersjs/feathers-sync#5]
I'm puzzled here... I installed `feathers-sync` and it's present in `package.json` as well as in my `node_modules` folder. But when I require it in my code, I am still getting `Error: Cannot find module 'feathers-sync'`... I have tried reinstalling it many times and that didn't solve the problem. The entry in my `package.json` says `"feathers-sync": "^0.1.0"`.

**Comment by daffl** [comment]
Well I guess ignoring the `src/` folder when publishing does that :wink: I published a v0.1.1 that should include it.

**Comment by mastertinner** [comment]
thanks for the quick fix, @daffl!
