### ISSUE TITLE
Scale server on kubernetes

### ISSUE THREAD

**Issue by kozzztya** [feathersjs/feathers-sync#55]
I have multiple replicas of one FeathersJS app in kubernetes. I open access to it with Service NodePort. On the client side I successfully connect to one replica, but with many replicas I have `xhr poll error`. The client connects to the server. It can even receive events sometimes, but on polling, I have an error. 
As far as I see I have a problem because of round robin connection. The client connects to one container but then polls another. 
Maybe I'm wrong and there is another reason of this error. Have anyone an experience with kubernetes and socket scaling? How properly use it?

**Comment by daffl** [comment]
With your setup I would force Socket.io to only use Websockets and not polling. As outlined [here on Stackoverflow](http://stackoverflow.com/questions/28238628/socket-io-1-x-use-websockets-only) this should be possible by either doing

```js
var socket = io({transports: ['websocket'], upgrade: false});
```

On the client or

```js
io.set('transports', ['websocket']);
```

On the server.

**Comment by kozzztya** [comment]
It works. Thank you.
