### ISSUE TITLE
Little question i am Missing Something?

### ISSUE THREAD

**Issue by frank-dspeed** [feathersjs/feathers-sync#68]
This only shares events right? so the same events that i get when i connect with a client to each instance and listen on it?

I am just wondering because i want to code a remote socket based api for a fingerprint reader and feathers looks like it will not fit ??? i need to send commands and get callbacks from diffrent fingerprinters on diffrent devices.

ideal would be all the fingerprinters and clients connect to a single server and using the fingerprint service like emit cmd ... callback but i don't get how to do that

**Comment by daffl** [comment]
You don't have to worry about `feathers-sync` if you are running only one instance (server) of the application.

I'd start with setting up a single server, have all readers connect to it and send their data as [normal socket requests](https://docs.feathersjs.com/api/socketio.html#direct-connection).

**Comment by frank-dspeed** [comment]
@daffl i go a totall new way because the device need to process a lot of commands like enroll 1 and wait and 2  and so on .......

i will now go with a database based async process que for the devices so i have better status reporting also i will use feathers to emit the result back and for placing the jobs !

**Comment by daffl** [comment]
Makes sense. Closing this one then.
